export const STRINGS_ENG = {
    0: 'hello',
    1: 'lorem ipsum ENG',
    2: 'Wybrałeś Pół na pół. Prosimy komputer o odrzucenie losowo dwóch błędnych odpowiedzi:',
    3: 'Wybrałeś Telefon do przyjaciela. Zatem dzwonimy!',
    4: 'Witaj, {{ random_name }}! {{ name.capitalize()) }} gra właśnie o  {{ MONEY[i]) }} zł i potrzebuje Twojej pomocy.',
    5: 'Znasz już pytanie. Oczekujemy na Twoją odpowiedź!',
    6: '{{ andom_name.upper }}: Dobrze, postaram się pomóc.',
    7: '{{ random_name.upper }}": Hmmm...',
    8: 'Chyba znam poprawną odpowiedź na to pytanie. Według mnie jest to odpowiedź',
    9: 'Na szczęście wiem, jak Ci pomóc. Prawidłowa odpowiedź to',
    10: 'Ha! To akurat pamiętam ze studiów! To na pewno',
    11: 'To był jeden z niewielu wykładów, które pamiętam. Odpowiedź to',
    12: 'Nie mam pewności co do odpowiedzi na to pytanie. Obstawiam odpowiedź',
    13: 'Kurczę, wybacz mi, ale nie pamiętam tego dokładnie. Ale coś kojarzę, że to będzie',
    14: 'Oh! Akurat na tych zajęciach mnie nie było... Ale może zaznacz',
    15: 'Wstyd się przyznać, ale nie mam pewności. Ale raczej odpowiedź to',
    16: 'Dobrze. Jaka jest Twoja decyzja, {{ name.capitalize()) }}?',
    17: 'A więc prosimy o pomoc Publiczność w studiu!',
    18: 'Głosy publiczności rozkładają się następująco:',
    19: 'Dobrze, {{ name.capitalize()) }}. Jaka jest Twoja decyzja?',
    20: 'Hmmm...',
    21: 'O kurczę...',
    22:  'Ej, coś mi to mówi...',

};
