export const STRINGS_PL = {
    0: 'Cześć!',
    1: 'Jestem obecnie studentką drugiego roku analizy i\xA0przetwarzania danych na Wydziale Matematyki i\xA0Informatyki Uniwersytetu im. Adama Mickiewicza w Poznaniu. Wcześniej ukończyłam studia licencjackie z kognitywistyki, na której zainteresowałam się programowaniem i\xA0tematyką User Experience. Pierwsze linijki kodu pisałam w\xA0Pythonie i\xA0były to proste skrypty tworzone na zajęciach na uczelni. „Po godzinach” starałam się czytać i\xA0pisać więcej w\xA0tym języku i\xA0udało mi się stworzyć prostą wersję Milionerów. Zainteresowałam się także webdevelopmentem i\xA0później przeniosłam grę do aplikacji webowej napisanej w\xA0Angularze. Napisałam także miniblog, który wykorzystuje Pythona jako język backendowy. Na studiach magisterskich zaczęłam wykorzystywać Pythona do zastosowań z\xA0obszaru statystyki i\xA0uczenia maszynowego. Jednym z\xA0moich celów na najbliższy czas jest podniesienie poziomu swojej wiedzy właśnie z\xA0zakresu machine learningu i\xA0sztucznej inteligencji oraz stworzenie kilku niebanalnych projektów z\xA0tym związanych.',
    2: 'Projekty programistyczne',
    3: 'Milionerzy dla kognitywistów',
    4: 'Drobne programy',
    5: 'Prosta, ale funkcjonalna wersja gry w Milionerów z\xA0pytaniami z\xA0obszaru kognitywistyki. Gra dostępna w\xA0języku polskim.',
    6: 'Zagraj w nowych Milionerów',
    7: 'Miniblog o tematyce podróżniczej, na którym użytkownik może m.in. założyć konto, dodawać, komentować i\xA0lajkować posty.',
    8: 'Zobacz programy',
    9: 'Wykształcenie i doświadczenie zawodowe',
    10: 'Experience opis',
    11: 'Zobacz CV',
    12: 'Grafika konkursowa',
    13: 'Plakat konkursowy wykonany w formie grafiki komputerowej, promujący zachowanie bezpieczeństwa i&nbsp;dbanie o&nbsp;swoje zdrowie w&nbsp;miejscu pracy. Motywem przewodnim konkursu była Gra o&nbsp;Tron i&nbsp;ogólnie rozumiany motyw gamerski',
    14: 'Poznaj mnie!',
    15: 'Pozostałe',
    16: 'Kwestionariusze i badania',
    17: 'Test Predyspozycji Zawodowych na Stanowisko: Koordynator Żałoby',
    18: 'Projekt ten został zrealizowany w ramach przedmiotu Psychometria na Wydziale Nauk Społecznych UAM. Jest to mierzący cechy osobowości i predyspozycje zawodowe kwestionariusz, którego ostateczna wersja została zbudowana na podstawie badań pilotażowych i analizy statystycznej. Weryfikacji poddane zostało respektowanie takich zasad konstruowania kwestionariuszy i przeprowadzania badań, jak standaryzacja, rzetelność, trafność czy obiektywność. Do analizy statystycznej wykorzystano program SPSS Statistics.\n',
    19: 'Zobacz raport',
    20: 'Czy optymiści rzeczywiście patrzą na świat przez różowe okulary? Zależność między stopniem orientacji pozytywnej a kolorystycznymi reprezentacjami wydarzeń',
    21: 'Badania związane z tym, czy osoby pozytywnie nastawione do świata rzeczywiście postrzegają wydarzenia w innych barwach, zostało przeprowadzone w ramach przedmiotu Praca Empiryczna - Psychologia Pozytywna. Zaproponowaną (i&nbsp;uzasadnioną!) hipotezę sprawdzono empirycznie, przygotowując kwestionariusz mierzący poziom orientacji pozytywnej oraz sprawdzający ocenę wydarzeń poprzez subiektywny wybór kolorów, które się z nimi kojarzą. Badanie zostało przeprowadzone w tradycyjnej wersji papierowej oraz w&nbsp;wersji internetowej. Wyniki okazały się istotnie statystycznie.',
    22: 'Czy kolory mają wagi? Analiza wpływu koloru przedmiotu na ocenę jego ciężkości',
    23: 'Ten eksperyment dotyczył sprawdzenia tego, czy przedmioty różniące się minimalnie wagowo mogą zostać ocenione jako lżejsze i cięższe tylko dlatego, że mają określony kolor lub są zestawione z przedmiotem o innym, danym kolorze. Zadaniem osób badanych było ocenienie wagi przedmiotów w dwóch turach: najpierw nie widząc ich, a następnie mając możliwość ich obserwacji. Jest to projekt przeprowdzony w ramach przedmiotu Percepcja na Wydziale Nauk Społecznych.',
    24: 'Test Rozumienia Treści Niedosłownych',
    25: 'W ramach zajęć z Teorii Inteligencji stworzony został internetowy kwestionariusz, którego zadaniem było zbadanie umiejętności ludzi do identyfikacji w komunikatach sarkazmu, ironii, metafor czy innych środków przekazywania treści w&nbsp;sposób niedosłowny. Podobnie, jak w przypadku Testu Predyspozycji Zawodowych, pierwotna wersja testu była podstawą do badań pilotażowych, których wyniki, poddane analizie statystycznej, pozwoliły na wyciągniecie wniosków dotyczącej ostatecznej wersji kwestionariusza. Link do internetowego kwestionariusza znajduje się tutaj; https://docs.google.com/forms/d/1TSU6pl2no9Yfk-MgVdmBCCFq8zsaP91ZvHOt_vw-H8E/prefill',
    26: 'Education',
    27: 'Education opis',
    28: 'Umiejętności',
    29: 'Skills opis',
    30: 'O mnie',
    31: 'Projekty',
    32: 'User Experience',
    33: 'Programowanie',
    34: 'Kontakt',
    35: 'Projekty UX',
    36: 'Skrzappek',
    37: 'Infokioski dla turystów',
    38: 'PKP',
    39: 'Escape Room',
    40: '"Skrzappek" jest efektem pracy zespołowej w&nbsp;ramach przedmiotu Komunikacja człowiek-komputer. Począwszy od przeprowadzenia badań mających na celu zidentyfikowanie problemów i&nbsp;potrzeb ludzi w&nbsp;związku&nbsp;z&nbsp;tematem robienia prezentów, poprzez intensywne próby znalezienia sposobu na rozwiązanie tych problemów i&nbsp;zaprojektowanie najważniejszych funkcji tworzonego produktu, aż w&nbsp;końcu dzięki przeprowadzonym badaniom na użytkownikach przy pomocy papierowych prototypów - powstał "Skrzappek", czyli aplikacja mająca na celu dostarczanie pomysłów na prezenty dla konkretnych osób.',
    41: 'Zobacz Skrzappka',
    42: 'Interaktywny prototyp tablicy informacyjnej, która ma w\xA0sprawny i\xA0intuicyjny sposób dostarczać turystom informacji, których najczęściej szukają, będąc w\xA0obcym mieście.',
    43: 'Zobacz infokiosk',
    44: 'Opierając się na wynikach badań, które sugerują, że proces kupowania biletów kolejowych nie należy do najprzyjeniejszych i najłatwiejszych, przeprowadzone zostało badanie potrzeb podróżujących PKP oraz dokonano próby zaproponowania i&nbsp;zaprojektowania rozwiązania na zidentyfikowane problemy.\n',
    45: 'Zobacz projekt',
    46: 'Zajęcia z Projektowania Usług pozwoliły na zmierzenie się z&nbsp;próbą zaprojektowania czegoś innego, niż produkt cyfrowy. Motywem przedownim został temat niedziel wolnych od handlu, a sposród grupu wszystkich potencjalnych interesariuszy jako grupę odbiorców wybrano właścicieli miejsc rozrywkowych i&nbsp;rekreacyjnych. Badanie potrzeb tej grupy ostatecznie zawęziło grupę docelową do właścicieli escape roomów, dla których została przygotowana usługa pod postacią wyniesienia tradycyjnie pojmowanego roomu poza mury lokalu, czyli na przykład do zoo, ogrodu botanicznego czy zamku.',
    47: 'Zagraj w starych Milionerów',
    48: 'Aby zagrać w grę, kliknij w Run nad terminalem. Gra uruchomi się po pobraniu wymaganych paczek.',
    49: 'Trzylatek',
    50: 'Anagram',
    51: 'Zgadywanie liczby',
    52: 'Zgadywanie liczby przez komputer',
    53: 'Kółko i krzyżyk',
    54: 'Wisielec',
    55: 'Wojna jednokartowa',
    56: 'Wojna normalna',
    57: '',
    58: 'Opis trzylatka',
    59: 'Opis anagramu',
    60: 'Opis zgadywania liczb',
    61: 'Opis zgadywania liczb przez komputer',
    62: 'Opis kółko i krzyżyk',
    63: 'Opis wisielca',
    64: 'Opis wojny jednokartowej',
    65: 'Opis wojny normalnej',
    66: 'rozpoczęcie studiów I stopnia na kierunku:',
    67: 'rozpoczęcie studiów II stopnia na kierunku:',
    68: 'analiza i\xA0przetwarzanie danych',
    69: 'kognitywistyka',
    70: 'Uniwersytet im. Adama Mickiewicza w\xA0Poznaniu',
    71: 'Wydział Nauk Społecznych',
    72: 'tryb stacjonarny',
    73: 'Wydział Matematyki i\xA0Informatyki',
    74: 'Junior Web Administrator',
    75: 'Junior E\u2011learning Designer',
    76: 'WinStudio',
    77: 'Llidero',
    78: 'administracja platformy e\u2011learningowej, testowanie szkoleń e\u2011learningowych, wsparcie zespołu programistów',
    79: 'projektowanie ekranów szkoleń e\u2011learningowych',
    80: 'Pracownik magazynowy',
    81: 'Amazon Fulfillment Poland',
    82: 'realizacja zamówień klientów',
    83: 'ukończenie studiów I\xA0stopnia na kierunku:',
    84: 'ukończenie studiów II\xA0stopnia na kierunku:',
    85: 'ukończenie nauki w\xA0Liceum Ogólnokształcącym im. Bolesława Krzywoustego w\xA0Nakle nad Notecią',
    86: 'profil politechniczny',
    87: 'Podgląd',
    88: 'Kod',
    89: 'Stara wersja napisana w\xA0Pythonie',
    90: 'Nowa wersja napisana w\xA0Angularze',
    91: 'Napisane w\xA0Pythonie (Flasku)',
    92: 'Napisane w\xA0Angularze',
    93: 'Tiny Journeys',
    94: 'Konteneryzaca przy użyciu Dockera',
    95: 'Więcej',
    96: 'Stworzone przy pomoce Axure RP',
    97: 'Polska',
    98: 'Ekonomiczne organizowanie własnej pracy',
    99: 'Sprawne przyswajanie nowej wiedzy',
    100: 'Znajomość metodyki SCRUM',
    101: 'Umiejętność pracy w\xA0zespole',
    102: 'Logiczno-analityczne myślenie',
    103: 'Programy',
    104: 'Języki programowania',
    105: 'Technologie',
    106: 'Narzędzia',
    107: 'Python 3',
    108: 'podstawowy',
    109: 'średniozaawansowany',
    110: 'JavaScript',
    111: 'Język C',
    112: 'SQL (T-SQL)',
    113: 'HTML5',
    114: 'CSS3',
    115: 'Git',
    116: 'Jira',
    117: 'Moodle',
    118: 'Angular 2+',
    119: 'Bootstrap 4',
    120: 'jQuery',
    121: 'Flask',
    122: 'Gulp',
    123: 'Axure RP',
    124: 'Tableau',
    125: 'Articulate Storyline',
    126: 'IBM SPSS Statistics',
    127: 'Adobe inDesign',
    128: 'Dobra znajomość:',
    129: 'Znajomość:',
    130: 'Podstawowa znajomość:',
    131: 'Docker',
    132: 'Język R',
    133: 'PHP',
    134: 'Microsoft Excel',
    135: 'WordPress',
    136: 'LaTeX',
    137: 'Sass',
    138: 'NumPy',
    139: 'SciPy',
    140: 'MatPlotLib',
    141: 'Pandas',
    142: 'Django',
    143: 'Z\xA0tymi technologiami, językami, narzędziami i\xA0programami spędzam (lub spędzałam) najwięcej czasu. Myślę, że potrafię się w\xA0nich już całkiem dobrze odnaleźć i\xA0tworzyć przy ich pomocy coraz bardziej skomplikowane rzeczy. Nie jest to jeszcze jednak wysoce zaawansowany poziom i\xA0przy bardziej skomplikowanych zadaniach wciąż przydaje mi się pomoc.',
    144: 'Te technologie, języki, narzędzia i\xA0programy są mi znane na raczej wciąż podstawowym poziomie, lecz korzystam z\xA0nich coraz częściej i\xA0za każdym razem staram się uzupełniać wiedzę na ich temat o\xA0nowe funkcjonalności. Uczę się ich głównie „przy okazji”, gdy potrzebuję ich w\xA0swoim projekcie lub poznałam je na uczelni i\xA0będę w\xA0najbliższym czasie korzystać z\xA0nich jeszcze bardziej.',
    145: 'Tych technologii, języków, narzędzi i\xA0programów raczej rzadko używam lub korzystam z nich tylko na podstawowym poziomie. Wiem, do czego służą, jak działają oraz co można przy ich pomocy osiągnąć i\xA0w\xA0razie potrzeby jestem w\xA0stanie w\xA0dość szybkim czasie je bardziej przyswoić. ',

};
