export const STRINGS_ENG = {
    0: 'ENG Cześć! z tej strony Asia.',
    1: 'ENG Jestem obecnie studentką trzeciego roku kognitywistyki na Wydziale Nauk Społecznych Uniwersytetu im. Adama Mickiewicza w Poznaniu. Po ukończeniu studiów chciałabym podjąć pracę i rozwijać się w branży IT. Najbardziej interesuje mnie obszar User Experience, jednak nie chciałabym ograniczać swojej samorealizacji tylko do działań w&nbsp;UX. Swój czas poświęcam także na programowanie - uczę się zarówno technologii front-endowych (związanych z HTML, CSS, JavaScript), jak i&nbsp;rozwijam umiejętności back-endowe (póki co na razie tylko w Pythonie). Z racji tego, że dobrze czuję się także z matematyką i statystyką, planuję podjąć studia magisterskie na kierunku związanym z Data Science. Poza studiami pracuję w trybie weekendowym oraz nieregularnie w tygodniu. W&nbsp;ostatnim czasie w&nbsp;wolnych chwilach staram się jak najwięcej czasu poświęcić na zgłębianie wiedzy o User Experience i Usability, które są tematem mojej pracy licencjackiej (Percepcja w&nbsp;kontekście użytkownika). Zdobyte w&nbsp;ten sposób podstawy teoretyczne zamierzam wykorzystać w&nbsp;praktyce poprzez przykładne tworzenie projektów w&nbsp;ramach zajęć na uczelni, udział w&nbsp;grupowych kursach i&nbsp;projektach online, szukanie własnych pomysłów na badania i poprawę doświadczeń użytkowników oraz, mam nadzieję, poprzez odbycie zawodowych praktyk.',
    2: 'ENG Projekty programistyczne',
    3: 'ENG Milionerzy dla kognitywistów',
    4: 'ENG Drobne programy',
    5: 'ENG Wersja popularnego teleturnieju "Milionerzy", w&nbsp;której pula pytań jest ściśle związana z&nbsp;obszarem studiów kognitywistyczych. Gracz otrzymuje zadanie losowo wybrane z&nbsp;zewnętrznej puli pytań, może skorzystać z&nbsp;trzech kół ratunkowych lub wycofać się w&nbsp;każdym momencie gry. Wynik gracza zostaje zapisywany do zewnętrznego pliku.\n',
    6: 'ENG Zobacz Milionerów',
    7: 'ENG Jest to zbiór drobnych programów napisanych w języku Python, na przykład: Gra w Wisielca Zgadywanie liczb Gra w Wojnę Gra w kółki i Krzyżyk',
    8: 'ENG Zobacz programy',
    9: 'Education and work experience',
    10: 'Experience description',
    11: 'See Curriculum Vitae',
    12: 'ENG Grafika konkursowa',
    13: 'ENG Plakat konkursowy wykonany w formie grafiki komputerowej, promujący zachowanie bezpieczeństwa i&nbsp;dbanie o&nbsp;swoje zdrowie w&nbsp;miejscu pracy. Motywem przewodnim konkursu była Gra o&nbsp;Tron i&nbsp;ogólnie rozumiany motyw gamerski',
    14: 'ENG Poznaj mnie!',
    15: 'Others',
    16: 'ENG Kwestionariusze i badania',
    17: 'ENG Test Predyspozycji Zawodowych na Stanowisko: Koordynator Żałoby',
    18: 'ENG Projekt ten został zrealizowany w ramach przedmiotu Psychometria na Wydziale Nauk Społecznych UAM. Jest to mierzący cechy osobowości i predyspozycje zawodowe kwestionariusz, którego ostateczna wersja została zbudowana na podstawie badań pilotażowych i analizy statystycznej. Weryfikacji poddane zostało respektowanie takich zasad konstruowania kwestionariuszy i przeprowadzania badań, jak standaryzacja, rzetelność, trafność czy obiektywność. Do analizy statystycznej wykorzystano program SPSS Statistics.\n',
    19: 'ENG Zobacz raport',
    20: 'ENG Czy optymiści rzeczywiście patrzą na świat przez różowe okulary? Zależność między stopniem orientacji pozytywnej a kolorystycznymi reprezentacjami wydarzeń',
    21: 'ENG Badania związane z tym, czy osoby pozytywnie nastawione do świata rzeczywiście postrzegają wydarzenia w innych barwach, zostało przeprowadzone w ramach przedmiotu Praca Empiryczna - Psychologia Pozytywna. Zaproponowaną (i&nbsp;uzasadnioną!) hipotezę sprawdzono empirycznie, przygotowując kwestionariusz mierzący poziom orientacji pozytywnej oraz sprawdzający ocenę wydarzeń poprzez subiektywny wybór kolorów, które się z nimi kojarzą. Badanie zostało przeprowadzone w tradycyjnej wersji papierowej oraz w&nbsp;wersji internetowej. Wyniki okazały się istotnie statystycznie.',
    22: 'ENG Czy kolory mają wagi? Analiza wpływu koloru przedmiotu na ocenę jego ciężkości',
    23: 'ENG Ten eksperyment dotyczył sprawdzenia tego, czy przedmioty różniące się minimalnie wagowo mogą zostać ocenione jako lżejsze i cięższe tylko dlatego, że mają określony kolor lub są zestawione z przedmiotem o innym, danym kolorze. Zadaniem osób badanych było ocenienie wagi przedmiotów w dwóch turach: najpierw nie widząc ich, a następnie mając możliwość ich obserwacji. Jest to projekt przeprowdzony w ramach przedmiotu Percepcja na Wydziale Nauk Społecznych.',
    24: 'ENG Test Rozumienia Treści Niedosłownych',
    25: 'ENG W ramach zajęć z Teorii Inteligencji stworzony został internetowy kwestionariusz, którego zadaniem było zbadanie umiejętności ludzi do identyfikacji w komunikatach sarkazmu, ironii, metafor czy innych środków przekazywania treści w&nbsp;sposób niedosłowny. Podobnie, jak w przypadku Testu Predyspozycji Zawodowych, pierwotna wersja testu była podstawą do badań pilotażowych, których wyniki, poddane analizie statystycznej, pozwoliły na wyciągniecie wniosków dotyczącej ostatecznej wersji kwestionariusza. Link do internetowego kwestionariusza znajduje się tutaj; https://docs.google.com/forms/d/1TSU6pl2no9Yfk-MgVdmBCCFq8zsaP91ZvHOt_vw-H8E/prefill',
    26: 'Education',
    27: 'Education description',
    28: 'Skills',
    29: 'Skills description',
    30: 'About',
    31: 'Projects',
    32: 'User Experience',
    33: 'Programming',
    34: 'Get in touch',
    35: 'UX projects',
    36: 'Skrzappek',
    37: 'Interactive information board for tourists',
    38: 'PKP',
    39: 'Escape Room',
    40: 'ENG "Skrzappek" jest efektem pracy zespołowej w&nbsp;ramach przedmiotu Komunikacja człowiek-komputer. Począwszy od przeprowadzenia badań mających na celu zidentyfikowanie problemów i&nbsp;potrzeb ludzi w&nbsp;związku&nbsp;z&nbsp;tematem robienia prezentów, poprzez intensywne próby znalezienia sposobu na rozwiązanie tych problemów i&nbsp;zaprojektowanie najważniejszych funkcji tworzonego produktu, aż w&nbsp;końcu dzięki przeprowadzonym badaniom na użytkownikach przy pomocy papierowych prototypów - powstał "Skrzappek", czyli aplikacja mająca na celu dostarczanie pomysłów na prezenty dla konkretnych osób.',
    41: 'See Skrzappek',
    42: 'ENG Infokioski dla Turystów (polskich i&nbsp;zagranicznych) to projekt zrealizowany w&nbsp;ramach zajęć Usability na UAM. Interaktywna makieta ma w&nbsp;sprawny i&nbsp;intuicyjny sposób dostarczyć użytkownikom informacji, których najczęściej szukają, będąc w&nbsp;obcym mieście. Gdzie jest adres&nbsp;X? Jak tam dojechać? Czy w&nbsp;pobliżu znajdę jakiś bankomat? Gdzie mogę skorzystać z&nbsp;toalety? A&nbsp;czy jest tam dostępny Internet? Ten infokiosk udzieli odpowiedzi na te pytania, w&nbsp;dodatku jest w&nbsp;stanie zrobić to w&nbsp;kilku wariantach językowych.',
    43: 'See interactive information board',
    44: 'ENG Opierając się na wynikach badań, które sugerują, że proces kupowania biletów kolejowych nie należy do najprzyjeniejszych i najłatwiejszych, przeprowadzone zostało badanie potrzeb podróżujących PKP oraz dokonano próby zaproponowania i&nbsp;zaprojektowania rozwiązania na zidentyfikowane problemy.\n',
    45: 'See project',
    46: 'ENG Zajęcia z Projektowania Usług pozwoliły na zmierzenie się z&nbsp;próbą zaprojektowania czegoś innego, niż produkt cyfrowy. Motywem przedownim został temat niedziel wolnych od handlu, a sposród grupu wszystkich potencjalnych interesariuszy jako grupę odbiorców wybrano właścicieli miejsc rozrywkowych i&nbsp;rekreacyjnych. Badanie potrzeb tej grupy ostatecznie zawęziło grupę docelową do właścicieli escape roomów, dla których została przygotowana usługa pod postacią wyniesienia tradycyjnie pojmowanego roomu poza mury lokalu, czyli na przykład do zoo, ogrodu botanicznego czy zamku.',
    47: 'Play Millionaire',
    48: 'ENG Aby zagrać w grę, kliknij w Run nad terminalem. Gra uruchomi się po pobraniu wymaganych paczek.',
    49: 'ENG Trzylatek',
    50: 'ENG Anagram',
    51: 'ENG Zgadywanie liczby',
    52: 'ENG Zgadywanie liczby przez komputer',
    53: 'ENG Kółko i krzyżyk',
    54: 'ENG Wisielec',
    55: 'ENG Wojna jednokartowa',
    56: 'ENG Wojna normalna',
    57: 'ENG ',
    58: 'ENG Opis trzylatka',
    59: 'ENG Opis anagramu',
    60: 'ENG Opis zgadywania liczb',
    61: 'ENG Opis zgadywania liczb przez komputer',
    62: 'ENG Opis kółko i krzyżyk',
    63: 'ENG Opis wisielca',
    64: 'ENG Opis wojny jednokartowej',
    65: 'ENG Opis wojny normalnej',
    66: 'taking up bachelor studies in:',
    67: 'taking up master studies in:',
    68: 'data analysis and processing',
    69: 'cognitive science',
    70: 'Adam Mickiewicz University in Poznań',
    71: 'Faculty of Social Sciences',
    72: 'full-time studies',
    73: 'Faculty of Mathematics and Computer Science ',
    74: 'Junior Web Administrator',
    75: 'Junior E-learning Designer',
    76: 'WinStudio',
    77: 'Llidero',
    78: 'e-learning platform administration, testing e-learning courses, supporting developers team',
    79: 'designing e-learning courses',
    80: 'Fulfillment Associate',
    81: 'Amazon Fulfillment Poland',
    82: 'customers\' order fulfillment',
    83: 'graduation from bachelor studies in:',
    84: 'graduation from master studies in:',
    85: 'graduation from Bolesław Krzywousty General Secondary School in Nakło nad Notecią',
    86: 'polytechnics',
    87: 'Preview',
    88: 'Source code',
    89: 'Old version made with Python',
    90: 'New version made with Angular',
    91: 'Made with Python (Flask)',
    92: 'Made with Angular',
    93: 'Tiny Journeys'
};
